import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {fixture,waitRun} from '../test-support/fixture.js';
import {id,sha256} from '../src/core.js';
import {defaultSettings} from '../src/settings.js';
function blankPDF(){let s='%PDF-1.4\n',offsets=[0];const objs=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] /Contents 4 0 R >>','<< /Length 0 >>\nstream\n\nendstream'];objs.forEach((o,i)=>{offsets.push(Buffer.byteLength(s));s+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=Buffer.byteLength(s);s+='xref\n0 5\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return Buffer.from(s);}
test('PDF is parsed, vocabulary is reviewed before publishing, versions freeze and explicit equivalent cache migration retains artifact',async t=>{
  const {service,config,demo}=await fixture(t),settings=defaultSettings(config);await assert.rejects(service.media.register(Readable.from([Buffer.from('%PDF-fake%%EOF')]),'application/pdf','invalid.pdf'),{code:'PDF_VALIDATION_FAILED'});
  const pdf=await service.media.register(Readable.from([blankPDF()]),'application/pdf','synthetic-blank.pdf');const extraction=await service.createVocabularyExtraction({client_request_id:id(),pdf_asset_id:pdf.asset_id,settings,consent_confirmed:true});assert.equal((await waitRun(service,extraction.run_id)).status,'awaiting_approval');const draft=await service.store.read(`runs/${extraction.run_id}/vocabulary-draft.json`);assert.equal(draft.extraction.mock,true);assert.equal(draft.vocabulary.source_pdf_sha256,pdf.sha256);const approved=await service.approveVocabulary(extraction.run_id,{...draft,approved_by:'local-test'});assert.equal(approved.extraction.pdf_sha256,pdf.sha256);assert.equal((await service.status(extraction.run_id)).status,'succeeded');await assert.rejects(service.registerVocabulary({...approved.vocabulary,source_pdf_sha256:'changed'},approved.discriminators,{approved_by:'local-test'}),{code:'VERSION_HASH_CONFLICT'});
  const body={client_request_id:id(),input_video_id:demo.actual_video_id,standard_set_id:demo.standard_set_id,analysis_strategy:'text_only',analysis_mode:'few_shot',settings,consent_confirmed:true},run=await service.createAnalysis(body);assert.equal((await waitRun(service,run.run_id)).status,'succeeded');const original=await service.result(run.run_id),set=await service.getSet(demo.standard_set_id),gt=await service.store.read(set.build_only_gt.asset_ref),g=await service.registerGT(gt);const build=await service.createStandard({client_request_id:id(),name:'新セット版',source_video_id:demo.standard_video_id,build_gt_asset_id:g.build_gt_asset_id,vocabulary_ref:demo.vocabulary_ref,profiles:['unguided','guided'],generate_images:true,settings,consent_confirmed:true});assert.equal((await waitRun(service,build.run_id)).status,'awaiting_approval');await service.approve(build.standard_set_id,'local-test');
  await assert.rejects(service.createAnalysis({...body,client_request_id:id(),standard_set_id:build.standard_set_id,stage1_artifact_id:original.stage1.artifact_id}),{code:'INCOMPATIBLE_STAGE1'});const migration=await service.migrateArtifact({artifact_id:original.stage1.artifact_id,standard_set_id:build.standard_set_id,analysis_strategy:'text_only',settings,reason:'標準セット変更、実入力全体が同一',editor:'local-test'});assert.equal(migration.artifact_sha256,original.stage1.artifact_sha256);const migrated=await service.createAnalysis({...body,client_request_id:id(),standard_set_id:build.standard_set_id,stage1_artifact_id:original.stage1.artifact_id});assert.equal((await waitRun(service,migrated.run_id)).status,'succeeded');assert.equal((await service.result(migrated.run_id)).stage1.artifact_id,original.stage1.artifact_id);assert.deepEqual(await service.result(run.run_id),original);
  await service.retire(build.standard_set_id);await service.deleteSetMedia(build.standard_set_id);assert.equal((await service.getSet(build.standard_set_id)).status,'retired');assert.equal(sha256(await service.result(run.run_id)),sha256(original));
});
