import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fixture,waitRun} from '../test-support/fixture.js';
import {TasService} from '../src/pipeline.js';
import {defaultSettings} from '../src/settings.js';
import {id,delay,sha256} from '../src/core.js';
import {CleanupLedger} from '../src/cleanup.js';
import {LocalStore} from '../src/store.js';
import {createAppServer,loadConfig} from '../server.js';
const request=(demo,config,patch={})=>({client_request_id:id(),input_video_id:demo.actual_video_id,standard_set_id:demo.standard_set_id,analysis_strategy:'text_only',analysis_mode:'few_shot',settings:defaultSettings(config),consent_confirmed:true,...patch});
test('jobs preserve failed Stage2 and reuse Stage1 on retry; reject time injection and incompatible guided artifact',async t=>{
  const {service,config,demo}=await fixture(t),input=request(demo,config,{faults:{invalid_stage2:true}});const first=await service.createAnalysis(input);assert.equal((await waitRun(service,first.run_id)).status,'failed');const failed=await service.status(first.run_id);assert.equal(failed.error.code,'INVALID_STAGE2');assert.equal(failed.result_available,false);assert.equal((await service.createAnalysis(input)).run_id,first.run_id);await assert.rejects(service.createAnalysis({...input,analysis_mode:'zero_shot'}),{code:'IDEMPOTENCY_CONFLICT'});
  const next=await service.retry(first.run_id,id());assert.equal((await waitRun(service,next.run_id)).status,'succeeded');const result=await service.result(next.run_id);assert.equal(result.stage1.artifact_id,failed.stage1.artifact_id);assert.equal(result.attempts.length,1);await assert.rejects(service.createAnalysis(request(demo,config,{analysis_strategy:'vocabulary_guided',stage1_artifact_id:result.stage1.artifact_id})),{code:'INCOMPATIBLE_STAGE1'});await assert.rejects(service.createAnalysis(request(demo,config,{gt:{segments:[]}})),{code:'INVALID_INPUT'});
  await assert.rejects(service.rederiveSafety(next.run_id,{client_request_id:id(),safety_policy:{...config.safety_policy,...defaultSettings(config).safety_policy,review_threshold:.8}}),{code:'VERSION_HASH_CONFLICT'});
  const derived=await service.rederiveSafety(next.run_id,{client_request_id:id(),safety_policy:{...defaultSettings(config).safety_policy,safety_policy_version:'test-safety.v2',review_threshold:.9}});assert.equal((await waitRun(service,derived.run_id)).status,'succeeded');const d=await service.result(derived.run_id);assert.equal(d.derivation.model_recalled,false);assert.deepEqual(d.segments.map(s=>[s.start_s,s.end_s,s.confidence_raw]),result.segments.map(s=>[s.start_s,s.end_s,s.confidence_raw]));assert.equal(d.attempts.length,0);
  const normal=service.model;normal.config.mockDelayMs=200;service.model={call:args=>normal.call({...args,signal:undefined})};const late=await service.createAnalysis(request(demo,config));for(let n=0;n<500;n++){if((await service.status(late.run_id)).status==='stage2_running')break;await delay(10);}await service.cancel(late.run_id);const cancelled=await waitRun(service,late.run_id);assert.equal(cancelled.status,'cancelled');assert.equal(cancelled.result_available,false);assert.equal((await service.store.read(`runs/${late.run_id}/run.json`)).attempts.length,1,'late raw response is retained without publishing success');
});
test('explicit cancellation and server restart preserve committed artifacts and recover queued work',async t=>{
  let {service,config,demo}=await fixture(t);let readyId;service.hooks.phase=async(r,status)=>{if(status==='stage1_ready'){readyId=r.run_id;await delay(60000,service.controller.signal);}};
  const running=await service.createAnalysis(request(demo,config));for(let i=0;i<500&&!readyId;i++)await delay(10);assert.equal(readyId,running.run_id);await service.cancel(running.run_id);assert.equal((await waitRun(service,running.run_id)).status,'cancelled');assert.equal((await service.status(running.run_id)).result_available,false);
  readyId=null;const interrupted=await service.createAnalysis(request(demo,config));for(let i=0;i<500&&!readyId;i++)await delay(10);assert.equal(readyId,interrupted.run_id);await service.close();assert.equal((await service.status(interrupted.run_id)).status,'interrupted');
  const queued=await service.createAnalysis(request(demo,config));assert.equal(queued.status,'queued');service=new TasService(config);t.after(()=>service.close());await service.ready;assert.equal((await waitRun(service,queued.run_id)).status,'succeeded');const retry=await service.retry(interrupted.run_id,id());assert.equal((await waitRun(service,retry.run_id)).status,'succeeded');assert.equal((await service.result(retry.run_id)).stage1.artifact_id,(await service.status(interrupted.run_id)).stage1.artifact_id);
  const record=await service.store.read(`runs/${retry.run_id}/run.json`);record.status='persisting';record.result_sha256=null;await service.store.write(`runs/${retry.run_id}/run.json`,record);await service.close();service=new TasService(config);await service.ready;assert.equal((await service.status(retry.run_id)).status,'succeeded');assert.equal((await service.status(retry.run_id)).result_available,true);
});
test('cleanup retries 403 beyond 24h, protects sessions and remote unknown grace, reconciles restart',async t=>{
  const root=path.resolve('.local-validation',`ledger-${id()}`),store=new LocalStore(root);await store.init();let clock=Date.now(),fail=true;const cfg={mockMode:true,bucket:null,graceMs:7200000};const ledger=new CleanupLedger(store,cfg,null,{clock:()=>clock,failRemove:async()=>{if(fail)throw Object.assign(new Error('403'),{code:'HTTP_403'});}});const r='test-run';await store.write(`runs/${r}/run.json`,{status:'interrupted',remote_outcome_unknown:true});const e=await ledger.registerLocal('temporary/test.tmp',r);await fs.mkdir(path.dirname(store.resolve(e.local_ref)),{recursive:true});await fs.writeFile(store.resolve(e.local_ref),'temporary');await ledger.recover();assert.equal((await ledger.summary(r)).cleanup_status,'waiting_lease');clock+=7200001;await ledger.sweep();let saved=await store.read(`cleanup/${e.asset_id}/entry.json`);assert.equal(saved.cleanup_status,'retry_wait');assert.equal(Date.parse(saved.next_retry_at)-clock,60000);clock+=86400000;await ledger.sweep();assert.equal((await ledger.summary(r)).cleanup_status,'cleanup_failed');fail=false;await ledger.sweep(true);assert.equal((await ledger.summary(r)).cleanup_status,'deleted');assert.equal(await store.exists(e.local_ref),false);
  await store.write('comparison-sessions/session/session.json',{status:'open',expires_at:new Date(clock+86400000).toISOString()});const shared=await ledger.upload({sha256:'synthetic',asset_ref:'none'},r,'session');await ledger.releaseRun(r);await ledger.upload({sha256:'synthetic',asset_ref:'none'},'second','session');await ledger.releaseRun('second');await ledger.sweep(true);assert.equal((await ledger.summary('second')).cleanup_status,'waiting_lease');await store.write('comparison-sessions/session/session.json',{status:'closed',expires_at:new Date(clock).toISOString()});await ledger.sweep(true);assert.equal((await ledger.summary('second')).cleanup_status,'deleted');assert.equal(shared.cleanup_asset_id,(await ledger.summary('second')).ledger_ids[0]);
});
test('HTTP polling disconnect does not cancel persistent run; local token remains mandatory',async t=>{
  const {service,config,demo}=await fixture(t);const app=createAppServer({...loadConfig({}),...config,port:0},{tasService:service});
  // The public server accepts a service factory option (the normal route uses the same instance).
  app.tas=()=>service;await new Promise(resolve=>app.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>app.close(resolve)));
  // This test exercises a real poll client disconnect against the standard HTTP route.
  const base=`http://127.0.0.1:${app.address().port}`;const session=await (await fetch(base+'/api/session')).json();const denied=await fetch(base+'/api/analysis-runs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request(demo,config))});assert.equal(denied.status,403);
  const created=await fetch(base+'/api/analysis-runs',{method:'POST',headers:{'content-type':'application/json','x-local-token':session.token},body:JSON.stringify(request(demo,config))});const run=await created.json();assert.equal(created.status,202,JSON.stringify(run));const abort=new AbortController();const polling=fetch(base+`/api/analysis-runs/${run.run_id}`,{signal:abort.signal});abort.abort();await polling.catch(()=>{});assert.equal((await waitRun(service,run.run_id)).status,'succeeded');
  const exported=await fetch(base+`/api/analysis-runs/${run.run_id}/result?download=1`);assert.match(exported.headers.get('content-disposition'),/attachment; filename="MOCK_.*_prediction.json"/);const result=await exported.json();assert.equal(result.schema_version,'tas-result.v1');assert.equal(result.mock,true);assert.equal(sha256(result),sha256(await service.result(run.run_id)));
});
