import fs from 'node:fs/promises';
import path from 'node:path';
import {createReadStream} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {LocalStore,safeId} from '../../src/store.js';
import {tasConfig,normalizeSettings} from '../../src/settings.js';
import {id,sha256,clone,demand,segmentId,profileFor} from '../../src/core.js';
import {loadPrompts,buildStage1,buildStage2,inputSignature,profileConditions} from '../../src/inputs.js';
import {validateGT,validateStage1,joinFixed,saveStage2,FIELDS} from '../../src/contracts.js';
import {GeapAdapter,GcsAdapter} from '../../src/geap.js';
import {MockModelAdapter} from '../../src/mock-model.js';
import {MediaTools,hashFile} from '../../src/media.js';
import {CleanupLedger} from '../../src/cleanup.js';
import {estimateCost} from '../../src/cost.js';
import {SCORING_VERSION,REFERENCE,scoreTAS,aggregate,checkSegmentationStructure,checkSafetyNet,fixedMetrics,routineMetrics,pairedEvidence,windowScores,ratio} from './scoring.mjs';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const SCENARIOS=['normal','reordered','repeated','omitted','rework'];
const STRATEGIES=['text_only','vocabulary_guided','visual_evidence'];
const MODES=['zero_shot','few_shot'];
const json=async p=>JSON.parse(await fs.readFile(p,'utf8'));
const anonymous=gt=>gt.segments.map(({start_s,end_s},i)=>({segment_id:segmentId(i),start_s,end_s}));
function freeformObservation(o){return {...Object.fromEntries(FIELDS.map(f=>[f,{status:f==='operation'?'observed':'not_applicable',value:f==='operation'?o.description:null,evidence_ids:f==='operation'?o.evidence.map(e=>e.evidence_id):[]} ])),unobserved_occlusions:FIELDS.filter(f=>f!=='operation').map(field=>({field,reason:'診断用自由記述。項目率はN/A。',evidence_ids:[]})),insufficient_discriminative_features:o.insufficient_discriminative_features,insufficiency_reasons:o.insufficiency_reasons,evidence:o.evidence};}
function fixedFreeform(output,boundaries,video,settings){demand(output?.schema_version==='probe.stage1.freeform.fixed.v1'&&Object.keys(output).length===2&&Array.isArray(output.observations),'INVALID_FREEFORM','自由記述の構造違反');for(const o of output.observations)demand(Object.keys(o).sort().join()===['segment_id','description','insufficient_discriminative_features','insufficiency_reasons','evidence'].sort().join()&&typeof o.description==='string'&&o.description.trim(),'INVALID_FREEFORM','自由記述項目違反');const adapted={schema_version:'stage1.fixed.v1',observations:output.observations.map(o=>({segment_id:o.segment_id,observation:freeformObservation(o)}))};validateStage1(adapted,{duration_s:video.duration_s,audio_enabled:settings.audio_enabled,boundaries});return joinFixed(adapted,boundaries);}
function freeformBody(built,artifact,set,mode,prompts){const body=clone(built.body),raw=new Map(artifact.output.observations.map(o=>[o.segment_id,o]));const part=body.contents[0].parts[0],input=JSON.parse(part.text);input.intervals=input.intervals.map(s=>{const {segment_id,description,insufficient_discriminative_features,insufficiency_reasons,evidence}=raw.get(s.segment_id);return {segment_id,start_s:s.start_s,end_s:s.end_s,description,insufficient_discriminative_features,insufficiency_reasons,evidence};});input.examples=mode==='few_shot'?[...set.freeform_examples].sort((a,b)=>a.label.job_no<b.label.job_no?-1:a.label.job_no>b.label.job_no?1:a.example_id.localeCompare(b.example_id)):[];part.text=JSON.stringify(input);body.systemInstruction.parts.push({text:prompts.loaded.freeform_stage2.text});return body;}
function validateFreeformStage2(raw,input,policy){const adapted=clone(raw);for(const l of adapted.labels??[])for(const ref of [...(l.evidence_refs??[]),...(l.candidates??[]).flatMap(c=>c.evidence_refs??[])])if(['observation','example'].includes(ref.kind)){demand(ref.field==='description','INVALID_FREEFORM_REF','自由記述の根拠fieldはdescription');ref.field='operation';}const saved=saveStage2(adapted,input,policy);for(const l of saved.output.labels)for(const ref of [...l.evidence_refs,...l.candidates.flatMap(c=>c.evidence_refs)])if(['observation','example'].includes(ref.kind))ref.field='description';return saved;}
function observationStats(artifact){if(artifact.description_format==='freeform_control')return {field_unknown_rate:null,observed_fields:null,self_report:ratio(artifact.output.observations.filter(o=>o.insufficient_discriminative_features).length,artifact.output.observations.length)};const rows=artifact.segments.map(s=>s.observation),fields=rows.flatMap(o=>FIELDS.map(f=>o[f]));return {field_unknown_rate:ratio(fields.filter(f=>f.status==='unknown').length,fields.length),observed_fields:fields.filter(f=>f.status==='observed').length,self_report:ratio(rows.filter(o=>o.insufficient_discriminative_features).length,rows.length)};}
export function datasetCoverage(manifest,cases){return Object.fromEntries(SCENARIOS.map(s=>{const selected=cases.filter(c=>c.scenario===s),min=manifest.split==='holdout'?3:1,long=selected.filter(c=>c.duration_s>=1080&&c.duration_s<=1320);return [s,{unique_videos:new Set(selected.map(c=>c.source_sha256)).size,minimum:min,long_videos:long.length,complete:new Set(selected.map(c=>c.source_sha256)).size>=min&&(manifest.split!=='holdout'||long.length>=1)}];}));}
export function scoreRecord(record){const {segments,gt,duration_s,status,groups=[],video_id}=record;return {run_id:record.run_id,check:record.check,condition:record.condition,case_id:record.case_id,repetition:record.repetition,scenario:record.scenario,split:record.split,status,tas:scoreTAS(segments,gt,duration_s,{status,vocabulary:record.vocabulary}),fixed:record.check===7&&status==='succeeded'?fixedMetrics(segments,gt):null,safety:checkSafetyNet(segments,gt,duration_s,{status}),structure:record.stage1?.segments?checkSegmentationStructure(record.stage1.segments,gt,duration_s):{status:'SKIP',oracle_MoF:null},routine:status==='succeeded'?routineMetrics(segments,gt):null,groups:status==='succeeded'?groups.map(g=>({group_id:g.group_id,selection_reason:g.selection_reason,windows:windowScores(segments,gt,g.windows||[],video_id),confusion:groupConfusion(segments,gt,duration_s,g.job_nos,record.check===7)})):[]};}
function groupConfusion(pred,gt,d,jobNos,fixed){const s=fixed?fixedMetrics(pred,gt):scoreTAS(pred,gt,d),entries=Object.entries(s.confusion).filter(([l])=>jobNos.includes(JSON.parse(l)[0])),counts=Object.fromEntries(entries),row_normalized=Object.fromEntries(entries.map(([g,row])=>{const total=Object.values(row).reduce((a,b)=>a+b,0);return [g,Object.fromEntries(Object.entries(row).map(([p,n])=>[p,ratio(n,total)]))];}));return {unit:fixed?'intervals':'10Hz_frames',counts,row_normalized,MoC:entries.length?entries.reduce((n,[g,row])=>n+(row[g]||0)/Object.values(row).reduce((a,b)=>a+b,0),0)/entries.length:null};}
export function aggregateBy(records,scores){const axes=['scenario','condition','repetition'];return Object.fromEntries(axes.map(key=>[key,Object.fromEntries([...new Set(records.map(r=>String(r[key])))].map(v=>[v,aggregate(scores.filter(s=>String(s[key])===v).map(s=>s.tas))]))]));}

export async function runAdditionalChecks({env=process.env,checks=[7,8,9,10,11]}={}){
  const evaluationId=id(),root=path.resolve(env.GEAP_EVAL_OUT_ROOT||path.join(ROOT,'tools/geap-probe/runs'),evaluationId),store=new LocalStore(root);await store.init();
  const config={...tasConfig({...env,MOCK_MODE:env.GEAP_PROBE_MOCK==='true'?'true':'false'}),dataRoot:root};
  const media=new MediaTools(config,store),cleanup=new CleanupLedger(store,config,new GcsAdapter(config)),model=config.mockMode?new MockModelAdapter(config):new GeapAdapter(config);
  const requested=[...checks],summary={evaluation_run_id:evaluationId,schema_version:'geap-check-summary.v1',implementation_version:'round18-probe.v1',mock:config.mockMode,data_origin:config.mockMode?'synthetic_mock':'real_measurement',gate_status:'unverified',checks:[]};
  let manifest,settings,prompts,set,standardFreeform=null;const records=[],artifacts=[],attempts=[],missing=[],resolved={schema_version:'resolved-geap-eval.v1',evaluation_run_id:evaluationId,created_at:new Date().toISOString(),mock:config.mockMode,checks,reference:REFERENCE,scoring_version:SCORING_VERSION,hashes:{},order:[],cases:[]};
  const remember=async(file,name)=>{resolved.hashes[name]=await hashFile(file);return file;};
  const write=(ref,v)=>store.immutable(ref,v);
  let currentRun=evaluationId;const controller=new AbortController();const abort=()=>controller.abort();process.once('SIGINT',abort);process.once('SIGTERM',abort);
  const attempt=async(stage,built,extras={})=>{let attemptId;return model.call({stage,body:built.body,settings,signal:controller.signal,...extras,onRequest:async req=>{attemptId=id();await write(`requests/${attemptId}.json`,req.body);await store.write('inflight.json',{run_id:currentRun,stage,attempt_id:attemptId,sent_at:new Date().toISOString(),remote_outcome_unknown:true});},onAttempt:async a=>{await write(`responses/${attemptId}.json`,{raw:a.raw_response,payload:a.payload});attempts.push({attempt_id:attemptId,run_id:currentRun,stage,request_sha256:sha256(a.body),response_sha256:sha256({raw:a.raw_response,payload:a.payload}),request_ref:`requests/${attemptId}.json`,response_ref:`responses/${attemptId}.json`,usageMetadata:a.usage??null,usage_is_synthetic:config.mockMode,elapsed_ms:a.elapsed_ms,http_status:a.http_status,remote_outcome_unknown:a.remote_outcome_unknown,model_id:a.model_id,modelVersion:a.model_version,agentic_traces:a.agentic_traces??[]});await store.write('attempts.json',attempts);await store.write('inflight.json',{run_id:currentRun,stage,attempt_id:attemptId,remote_outcome_unknown:a.remote_outcome_unknown});if(a.remote_outcome_unknown)await cleanup.releaseRun(evaluationId,{unknown:true});}});};
  async function stage1(video,profile,boundaries,freeform=false){const producerRunId=id();currentRun=producerRunId;const built=buildStage1({video,settings,prompts,profile,boundaries,vocabulary:set.vocabulary,discriminators:set.discriminators,freeform});const res=await attempt('stage1',built,{video,boundaries,freeform});let segments;if(freeform)segments=fixedFreeform(res.output,boundaries,video,settings);else{validateStage1(res.output,{duration_s:video.duration_s,audio_enabled:settings.audio_enabled,boundaries});segments=boundaries?joinFixed(res.output,boundaries):res.output.segments;}const a={artifact_id:id(),producer_run_id:producerRunId,attempts:attempts.filter(a=>a.run_id===producerRunId),modelVersion:res.model_version,agentic_traces:res.agentic_traces??[],usageMetadata:res.usage,description_format:freeform?'freeform_control':'observation.v1',cache_namespace:freeform?'probe-freeform-fixed':'probe-observation',profile,boundary_mode:boundaries?'fixed':'discover',output:res.output,segments,request_sha256:sha256(built.body),input_signature_sha256:inputSignature(built.body,[video]),video_sha256:video.sha256,settings_sha256:sha256(settings),prompt_sha256:built.prompt.sha256,raw_response_ref:attempts.at(-1).response_ref};a.artifact_sha256=sha256(a);await write(`stage1/${a.artifact_id}.json`,a);artifacts.push(a);return a;}
  async function condition(c,video,a,strategy,mode,check,repetition,evidence_condition=null,stage1Error=null){
    const runId=id();currentRun=runId;const freeform=a?.description_format==='freeform_control',condition=`${freeform?'freeform_control':strategy}/${mode}${evidence_condition?'/'+evidence_condition:''}`,r={run_id:runId,check,case_id:c.case_id,video_id:c.video_id,condition,analysis_strategy:strategy,analysis_mode:mode,evidence_condition:evidence_condition??(strategy==='visual_evidence'?(mode==='few_shot'?'text_actual_video_standard_images':'text_actual_video'):'text'),description_format:freeform?'freeform_control':'observation.v1',repetition,scenario:c.scenario,split:manifest.split,stage1:a??null,duration_s:c.duration_s,gt:c.gt.segments,groups:c.groups,vocabulary:set.vocabulary,observability:c.observability,segments:[],status:'not_run',error:null,mock:config.mockMode,metrics:{}};
    const started=Date.now();try{if(stage1Error)throw stage1Error;if(controller.signal.aborted){r.status='cancelled';throw controller.signal.reason;}
      const images=[];if(strategy==='visual_evidence'&&mode==='few_shot'&&evidence_condition!=='text_actual_video')for(const image of set.representative_images)images.push(await cleanup.upload(image,evaluationId,null,controller.signal));
      const inputSet=freeform?{...set,examples:{...set.examples,unguided:standardFreeform.segments.map((s,i)=>({example_id:set.freeform_examples[i].example_id,label:set.freeform_examples[i].label,observation:s.observation}))}}:set;
      const built=buildStage2({segments:a.segments,video,settings,prompts,analysis_strategy:strategy,analysis_mode:mode,set:inputSet,vocabulary:set.vocabulary,discriminators:set.discriminators,images,evidence_condition});if(freeform)built.body=freeformBody(built,a,set,mode,prompts);
      const res=await attempt('stage2',built,{input:built.input,video});if(freeform&&config.mockMode)for(const l of res.output.labels)for(const ref of [...l.evidence_refs,...l.candidates.flatMap(c=>c.evidence_refs)])if(['observation','example'].includes(ref.kind))ref.field='description';
      await write(`stage2/${runId}-raw.json`,res.output);const saved=freeform?validateFreeformStage2(res.output,built.input,settings.safety_policy):saveStage2(res.output,built.input,settings.safety_policy);
      r.segments=a.segments.map(s=>{const l=saved.output.labels.find(l=>l.segment_id===s.segment_id);const {final_label,...rest}=l;return {...s,...rest,...final_label};});r.status='succeeded';r.input_sha256=sha256(built.body);r.warnings=saved.warnings;r.observation_stats=observationStats(a);r.standard_observation_stats=observationStats(freeform?standardFreeform:{segments:inputSet.examples[profileFor(strategy)].map(e=>({observation:e.observation}))});r.metrics.images=images.length;r.metrics.sent_media_bytes=(strategy==='visual_evidence'?video.size_bytes:0)+images.reduce((n,i)=>n+(i.size_bytes||0),0);
    }catch(e){r.status=r.status==='cancelled'||controller.signal.aborted?'cancelled':/AUTH|GEAP_HTTP|PERMISSION|REMOTE|UPLOAD|ENVIRONMENT/.test(e.code||'')?'communication_failed':'invalid';r.error={code:e.code||'INVALID_OUTPUT',message:e.message};}
    r.metrics.elapsed_ms=Date.now()-started;r.metrics.attempts=attempts.filter(x=>x.run_id===runId);r.metrics.cost=estimateCost(r.metrics.attempts,resolved.price_table??null,{mock:config.mockMode,attributedStage1:a?.attempts??[]});await write(`stage2/${runId}.json`,r);records.push(r);return r;
  }
  try{
    if(env.GEAP_EVAL_RUN){const prior=path.resolve(env.GEAP_EVAL_RUN);demand(checks.every(c=>[8,10].includes(c)),'INVALID_RESCORING','保存済み採点はCheck 8/10のみ');records.push(...await json(path.join(prior,'evaluation-records.json')));resolved.source_evaluation={path:prior,sha256:await hashFile(path.join(prior,'evaluation-records.json'))};await write('resolved-manifest.json',resolved);}
    else if(checks.every(c=>[8,10].includes(c)))missing.push('GEAP_EVAL_RUN（Check 8/10は保存済み出力のみ採点します）');
    else if(!env.GEAP_EVAL_MANIFEST)missing.push('GEAP_EVAL_MANIFEST');
    else{
      const manifestPath=path.resolve(env.GEAP_EVAL_MANIFEST),base=path.dirname(manifestPath);manifest=await json(await remember(manifestPath,'manifest'));demand(manifest.schema_version==='geap-eval-manifest.v1'&&['pilot','holdout'].includes(manifest.split),'INVALID_MANIFEST','評価manifestの版・splitを確認してください');demand(manifest.repetitions===3,'INVALID_REPETITIONS','反復数は3で固定してください');demand(JSON.stringify([...manifest.analysis_strategies].sort())===JSON.stringify([...STRATEGIES].sort())&&JSON.stringify([...manifest.analysis_modes].sort())===JSON.stringify([...MODES].sort()),'INVALID_CONDITIONS','3方式×2モードを指定してください');
      settings=normalizeSettings(await json(await remember(path.resolve(base,manifest.settings_ref),'settings')),config);prompts=await loadPrompts(settings.prompt_release);resolved.settings=settings;resolved.hashes.prompt_manifest=prompts.sha256;resolved.manifest=manifest;
      const scoring=await json(await remember(path.resolve(base,manifest.scoring_policy_ref),'scoring_policy'));demand(scoring.version===SCORING_VERSION&&scoring.sample_hz===10&&scoring.units?.rates==='ratio'&&scoring.units?.edit==='0..100','INVALID_SCORING_POLICY','採点ポリシーがRound 18と異なります');resolved.scoring_policy=scoring;if(env.GEAP_PRICE_TABLE)resolved.price_table=await json(await remember(path.resolve(env.GEAP_PRICE_TABLE),'price_table'));
      resolved.acceptance_policy=manifest.acceptance_policy_ref?await json(await remember(path.resolve(base,manifest.acceptance_policy_ref),'acceptance_policy')):null;
      const sourceStore=new LocalStore(path.resolve(env.DATA_ROOT||path.join(ROOT,'data')));set=await sourceStore.read(`standard-sets/${safeId(manifest.standard_set_id)}/published.json`);demand(set.status==='ready'&&set.content_sha256===sha256({...set,content_sha256:null}),'INVALID_SET','公開標準セットのハッシュが不一致');resolved.hashes.standard_set=sha256(set);resolved.standard_provenance=set.provenance;
      for(const profile of ['unguided','guided']){demand(set.description_profiles[profile]&&sha256(set.description_profiles[profile].conditions)===sha256(profileConditions(settings,prompts,profile)),'PROFILE_INCOMPATIBLE','標準・実作業の条件を揃えてください');const a=await sourceStore.read(`stage1-artifacts/${set.description_profiles[profile].artifact_id}/artifact.json`);demand(sha256(a)===set.description_profiles[profile].artifact_sha256,'INVALID_SET','標準artifactハッシュ不一致');resolved.hashes[`standard_${profile}`]=sha256(a);}
      demand(set.representative_images.length>0,'IMAGES_REQUIRED','全標準工程の代表画像が必要です');for(const image of set.representative_images){demand(image.standard_set_id===set.standard_set_id&&image.source_video_sha256===set.source_video.sha256&&image.gt_process_id&&Number.isFinite(image.extracted_time_s)&&image.selection_rule_version&&image.transform_version,'INVALID_IMAGE','代表画像の出自不足');const file=sourceStore.resolve(image.asset_ref);demand(await hashFile(file)===image.sha256,'INVALID_IMAGE','画像ハッシュ不一致');const target=`standard-inputs/${image.image_id}.jpg`;await fs.mkdir(path.dirname(store.resolve(target)),{recursive:true});await fs.copyFile(file,store.resolve(target));image.asset_ref=target;image.size_bytes=(await fs.stat(file)).size;resolved.hashes[`image_${image.image_id}`]=image.sha256;}
      for(const f of ['src/contracts.js','src/inputs.js','src/response-schemas.js','src/geap.js','src/media.js','public/segments.js','tools/geap-probe/scoring.mjs','tools/geap-probe/extra-checks.mjs'])await remember(path.join(ROOT,f),f);
      const cases=[];for(const entry of manifest.cases){const file=path.resolve(base,entry.inference.asset_ref),asset=await media.register(createReadStream(file),'video/mp4',entry.case_id);asset.video_id=entry.inference.video_id;const gt=await json(await remember(path.resolve(base,entry.scoring_only.gt_ref),`${entry.case_id}.gt`));validateGT(gt,asset,set.vocabulary);demand(SCENARIOS.includes(entry.scoring_only.scenario),'INVALID_SCENARIO','区分を事前指定してください');const groups=await json(await remember(path.resolve(base,entry.scoring_only.similar_groups_ref),`${entry.case_id}.groups`)),observability=await json(await remember(path.resolve(base,entry.scoring_only.observability_ref),`${entry.case_id}.observability`));demand(asset.sha256!==set.source_video.sha256,'DATASET_LEAK','標準と実評価動画は分離してください');const c={case_id:entry.case_id,video_id:asset.video_id,duration_s:asset.duration_s,source_sha256:asset.sha256,scenario:entry.scoring_only.scenario,asset,gt,groups,observability};cases.push(c);resolved.cases.push({case_id:c.case_id,video_id:c.video_id,duration_s:c.duration_s,source_sha256:c.source_sha256,scenario:c.scenario});}
      summary.coverage=datasetCoverage(manifest,cases);resolved.order=cases.flatMap(c=>Array.from({length:3},(_,i)=>{const conditions=STRATEGIES.flatMap(s=>MODES.map(m=>({strategy:s,mode:m})));return {case_id:c.case_id,repetition:i+1,conditions:[...conditions.slice(i),...conditions.slice(0,i)]};}));await write('resolved-manifest.json',resolved);
      if(!config.mockMode){demand(env.GEAP_EVAL_CONSENT_CONFIRMED==='true','CONSENT_REQUIRED','manifest全動画と標準動画・画像の送信同意が必要です');model.assertReady(settings);}
      if(checks.includes(7)){
        const source=await sourceStore.read(`media/${set.source_video.video_id}/asset.json`),asset=await media.register(createReadStream(sourceStore.resolve(source.asset_ref)),'video/mp4','標準自由記述対照');const gt=await sourceStore.read(set.build_only_gt.asset_ref);demand(sha256(gt)===set.build_only_gt.sha256,'INVALID_GT','標準GTハッシュ不一致');const prepared=await media.prepare(asset,settings,evaluationId,cleanup,controller.signal),video=await cleanup.upload(prepared,evaluationId,null,controller.signal);standardFreeform=await stage1(video,'unguided',anonymous(gt),true);set.freeform_examples=standardFreeform.segments.map((seg,i)=>{const o=standardFreeform.output.observations.find(o=>o.segment_id===seg.segment_id);return {example_id:id(),label:{job_no:gt.segments[i].job_no,job_title:gt.segments[i].job_title},description:o.description,insufficient_discriminative_features:o.insufficient_discriminative_features,insufficiency_reasons:o.insufficiency_reasons,evidence:o.evidence};});await write('standard-freeform.json',{artifact:standardFreeform,examples:set.freeform_examples});}
      for(const order of resolved.order){const c=cases.find(c=>c.case_id===order.case_id);currentRun=evaluationId;let video;try{const prepared=await media.prepare(c.asset,settings,evaluationId,cleanup,controller.signal);video=await cleanup.upload(prepared,evaluationId,null,controller.signal);}catch(e){for(const check of checks.filter(c=>[7,9,11].includes(c)))for(const cond of order.conditions)await condition(c,null,null,cond.strategy,cond.mode,check,order.repetition,null,e);continue;}
        const cache={};async function get(profile,fixed=false,freeform=false){const key=`${profile}/${fixed}/${freeform}`;if(!cache[key])try{cache[key]={artifact:await stage1(video,profile,fixed?anonymous(c.gt):null,freeform)};}catch(error){cache[key]={error};}return cache[key];}
        if(checks.includes(7)){for(const cond of order.conditions){const {artifact,error}=await get(profileFor(cond.strategy),true);await condition(c,video,artifact,cond.strategy,cond.mode,7,order.repetition,null,error);}for(const mode of MODES){const {artifact,error}=await get('unguided',true,true);await condition(c,video,artifact,'text_only',mode,7,order.repetition,null,error);}}
        if(checks.includes(9)||checks.includes(11)){if(checks.includes(9))for(const cond of order.conditions){const {artifact,error}=await get(profileFor(cond.strategy));await condition(c,video,artifact,cond.strategy,cond.mode,9,order.repetition,null,error);}
          if(checks.includes(11)){const {artifact,error}=await get('unguided');for(const evidence of ['text','text_actual_video','text_actual_video_standard_images']){const existing=records.find(r=>r.check===9&&r.case_id===c.case_id&&r.repetition===order.repetition&&r.analysis_mode==='few_shot'&&r.evidence_condition===evidence&&r.stage1?.artifact_id===artifact?.artifact_id);if(existing)records.push({...existing,check:11,reused_from_run_id:existing.run_id});else await condition(c,video,artifact,evidence==='text'?'text_only':'visual_evidence','few_shot',11,order.repetition,evidence,error);}}
        }
      }
    }
  }catch(e){missing.push(`${e.code||'EVALUATION_ERROR'}: ${e.message}`);}
  finally{process.removeListener('SIGINT',abort);process.removeListener('SIGTERM',abort);await cleanup.releaseRun(evaluationId);await cleanup.sweep();}
  await write('evaluation-records.json',records);const scores=records.map(scoreRecord);await write('scores.json',scores);
  for(const check of requested){const rs=records.filter(r=>check===8?r.check===9:check===10?[7,9,11].includes(r.check):r.check===check),ss=rs.map(scoreRecord);const failures=rs.filter(r=>r.status!=='succeeded').map(r=>({run_id:r.run_id,...r.error}));const metric=check===8?rs.filter((r,i,a)=>a.findIndex(x=>x.stage1?.artifact_id===r.stage1?.artifact_id)===i).map(r=>({artifact_id:r.stage1?.artifact_id,...scoreRecord(r).structure})):check===10?ss.map(s=>({run_id:s.run_id,...s.safety})):{aggregate:aggregate(ss.map(s=>s.tas)),by:aggregateBy(rs,ss)};
    const item={check_id:check,implementation_version:'round18-probe.v1',status:rs.length?(config.mockMode?'MOCK_VALIDATED':'MEASURED'):'SKIP',capability_verdict:rs.length?(failures.length?'FAIL':config.mockMode?'UNVERIFIED':'MEASURED'):'NOT_RUN',quality_verdict:'UNVERIFIED',run_ids:rs.map(r=>r.run_id),metrics:metric,failures,missing_inputs:[...missing,...(!rs.length?[check===8?'Check 9 discover成果物':check===10?'Check 7/9/11保存出力':'評価入力・実行']:[])],acceptance_policy_version:resolved.acceptance_policy?.version??null};
    if(check===11){item.paired=[];for(const b of rs.filter(r=>r.evidence_condition==='text'&&r.status==='succeeded'))for(const a of rs.filter(r=>r.case_id===b.case_id&&r.repetition===b.repetition&&r.evidence_condition!=='text'&&r.status==='succeeded'))item.paired.push({before_run_id:b.run_id,after_run_id:a.run_id,...pairedEvidence(b.segments,a.segments,b.gt),MoF_difference:scoreRecord(a).tas.Acc.value-scoreRecord(b).tas.Acc.value,auto_error_difference:(()=>{const x=scoreRecord(a).safety.auto_error.value,y=scoreRecord(b).safety.auto_error.value;return x===null||y===null?null:x-y;})()});item.human_evidence_audit={status:'NOT_RUN',queue:rs.filter(r=>r.status==='succeeded').map(r=>({run_id:r.run_id,segments:scoreRecord(r).safety.errors.filter(e=>e.E).map(e=>e.segment_id),correct_samples:scoreRecord(r).safety.errors.filter(e=>!e.E).sort((a,b)=>a.segment_id.localeCompare(b.segment_id)).slice(0,3).map(e=>e.segment_id)}))};item.operational_audit={status:'NOT_RUN',required:['18–22min scenarios','standard_build','image_extraction','upload','validation','persistence','cleanup','disconnect','cancel_stage1','cancel_stage2','429','500','token_expiry','timeout_unknown','cleanup_403','restart'],local_test_command:'node --test test/fewshot.test.js test/failure-paths.test.js test/geap-adapter.test.js'};}
    // A measured contract success is not an accuracy/operations gate. Human audit and
    // predeclared per-group/per-scenario policy must be signed off outside the probe.
    summary.checks.push(item);
  }
  summary.cleanup=await cleanup.summary(evaluationId);summary.attempts=attempts.length;summary.cost=estimateCost(attempts,resolved.price_table??null,{mock:config.mockMode});summary.settings=settings??null;summary.missing_inputs=missing;await write('summary.json',summary);return {root,summary};
}
