// Round 18 scoring. No inference or network access in this module.
export const SCORING_VERSION='tas-eval-round18.v1';
export const REFERENCE={repository:'https://github.com/yabufarha/ms-tcn',commit:'33ed91c0c7576650a2367efc602553af4c5295b1',file:'eval.py',differences:['10 Hz half-open sampling','all seven non-work labels retained','strict invalid-result handling','continuous-time diagnostics and safety metrics']};
export const ratio=(numerator,denominator)=>({numerator,denominator,value:denominator?numerator/denominator:null});
const label=s=>JSON.stringify([s.job_no,s.job_title]);
export const overlap=(p,g)=>Math.max(0,Math.min(p.end_s,g.end_s)-Math.max(p.start_s,g.start_s));
const duration=s=>s.end_s-s.start_s;
const iou=(p,g)=>overlap(p,g)/(Math.max(p.end_s,g.end_s)-Math.min(p.start_s,g.start_s));
const sum=(xs,fn=x=>x)=>xs.reduce((n,x)=>n+fn(x),0);
export function quantiles(values){const a=[...values].sort((a,b)=>a-b),n=a.length;return {count:n,median:n?(a[Math.floor((n-1)/2)]+a[Math.ceil((n-1)/2)])/2:null,p95:n?a[Math.ceil(.95*n)-1]:null};}
export function validIntervals(xs,d){return Array.isArray(xs)&&xs.length>0&&xs.every((x,i)=>Number.isFinite(x.start_s)&&Number.isFinite(x.end_s)&&x.end_s>x.start_s&&x.start_s===(i?xs[i-1].end_s:0))&&xs.at(-1).end_s===d;}
export function frames(segments,d){const a=[];let j=0;for(let n=0;n/10<d;n++){while(j+1<segments.length&&n/10>=segments[j].end_s)j++;a.push(segments[j]&&segments[j].start_s<=n/10&&n/10<segments[j].end_s?label(segments[j]):'__INVALID__');}return a;}
export function compress(a,d){const out=[];a.forEach((l,i)=>{if(!i||a[i-1]!==l)out.push({label:l,start_index:i,end_index:i+1,start_s:i/10,end_s:Math.min(d,(i+1)/10)});else{out.at(-1).end_index=i+1;out.at(-1).end_s=Math.min(d,(i+1)/10);}});return out;}
export function editScore(p,g){let row=Array.from({length:g.length+1},(_,i)=>i);for(let i=1;i<=p.length;i++){const next=[i];for(let j=1;j<=g.length;j++)next[j]=Math.min(next[j-1]+1,row[j]+1,row[j-1]+(p[i-1]===g[j-1]?0:1));row=next;}return Math.max(p.length,g.length)?100*(1-row[g.length]/Math.max(p.length,g.length)):100;}
export function f1Match(p,g,threshold){const used=new Set(),pairs=[];for(let i=0;i<p.length;i++){let best=-1,score=-1;for(let j=0;j<g.length;j++)if(p[i].label===g[j].label){const v=iou(p[i],g[j]);if(v>score){best=j;score=v;}}if(best>=0&&score>=threshold&&!used.has(best)){used.add(best);pairs.push([i,best]);}}const tp=pairs.length,fp=p.length-tp,fn=g.length-tp;return {tp,fp,fn,f1:ratio(2*tp,2*tp+fp+fn),pairs};}
function confusion(g,p){const matrix={};for(let i=0;i<g.length;i++){matrix[g[i]]??={};matrix[g[i]][p[i]]=(matrix[g[i]][p[i]]||0)+1;}return matrix;}
function classMetrics(matrix){const gt=Object.keys(matrix),union=new Set([...gt,...Object.values(matrix).flatMap(Object.keys)]);const rows=Object.fromEntries(gt.map(l=>[l,Object.fromEntries(Object.entries(matrix[l]).map(([p,n])=>[p,ratio(n,sum(Object.values(matrix[l])))]))]));const classes=[...union].sort().map(l=>{const truth=sum(Object.values(matrix[l]||{})),pred=sum(Object.values(matrix),r=>r[l]||0),correct=matrix[l]?.[l]||0;return {label:l,gt_frames:truth,predicted_frames:pred,correct,accuracy:ratio(correct,truth),iou:ratio(correct,truth+pred-correct)};});return {classes,row_normalized:rows,MoC:gt.length?sum(classes.filter(c=>c.gt_frames),c=>c.accuracy.value)/gt.length:null,mean_class_iou:classes.length?sum(classes,c=>c.iou.value)/classes.length:null};}
export function scoreTAS(pred,gt,d,{status='succeeded',vocabulary=null}={}){
  const attempted=status!=='not_run',complete=!['communication_failed','cancelled','not_run'].includes(status),invalid=status==='invalid'||(complete&&!validIntervals(pred,d));
  const g=frames(gt,d);if(!complete)return {status,attempted,completed:false,frame_count:g.length,correct_frames:0,Acc:null,Edit:null,F1:null,confusion:{},classes:[]};
  const p=invalid?g.map(()=>'__INVALID__'):frames(pred,d),gc=compress(g,d),pc=compress(p,d),matrix=confusion(g,p);
  const hits=g.reduce((n,l,i)=>n+(l===p[i]?1:0),0),f1=Object.fromEntries([10,25,50].map(t=>[t,f1Match(pc,gc,t/100)])),pairs=f1[50].pairs;
  const known=vocabulary?new Set(vocabulary.labels.map(label)):null,raw=Array.isArray(pred)?pred.filter(s=>typeof s.job_no==='string'&&typeof s.job_title==='string'):[];
  const vocabRate=known&&raw.length?ratio(raw.filter(s=>!known.has(label(s))).length,raw.length):ratio(0,0);
  return {status:invalid?'invalid':status,attempted,completed:true,frame_count:g.length,correct_frames:invalid?0:hits,Acc:ratio(invalid?0:hits,g.length),Edit:invalid?0:editScore(pc.map(s=>s.label),gc.map(s=>s.label)),F1:f1,confusion:matrix,...classMetrics(matrix),raw_vocabulary_outside:vocabRate,other_rate:ratio(raw.filter(s=>s.job_no==='NW07').length,raw.length),pair_errors:{pair_count:pairs.length,gt_count:gc.length,match_rate:ratio(pairs.length,gc.length),interval_iou:pairs.length?sum(pairs,([i,j])=>iou(pc[i],gc[j]))/pairs.length:null,boundary_seconds:quantiles(pairs.flatMap(([i,j])=>[Math.abs(pc[i].start_s-gc[j].start_s),Math.abs(pc[i].end_s-gc[j].end_s)])),duration_seconds:quantiles(pairs.map(([i,j])=>Math.abs(duration(pc[i])-duration(gc[j]))))}};
}
// Monotone one-to-one DP. Objective: count, score, lexicographically earliest index pairs.
export function monotoneMatch(p,g,weight){const empty={count:0,score:0,pairs:[]},dp=Array.from({length:p.length+1},()=>Array(g.length+1).fill(empty));const better=(a,b)=>{if(a.count!==b.count)return a.count>b.count?a:b;if(Math.abs(a.score-b.score)>1e-12)return a.score>b.score?a:b;for(let k=0;k<a.pairs.length;k++)for(let q=0;q<2;q++)if(a.pairs[k][q]!==b.pairs[k][q])return a.pairs[k][q]<b.pairs[k][q]?a:b;return a;};for(let i=p.length-1;i>=0;i--)for(let j=g.length-1;j>=0;j--){let best=better(dp[i+1][j],dp[i][j+1]);const w=weight(p[i],g[j]);if(w!==null){const tail=dp[i+1][j+1];best=better(best,{count:tail.count+1,score:tail.score+w,pairs:[[i,j],...tail.pairs]});}dp[i][j]=best;}return dp[0][0].pairs;}
export function checkSegmentationStructure(p,g,d){
  if(!validIntervals(p,d))return {status:'FAIL',reason:'INVALID_STAGE1',oracle_MoF:null,oracle_continuous:null};
  const substantial=(p,g)=>overlap(p,g)>=Math.min(1,.1*Math.min(duration(p),duration(g)));
  const merged=strict=>p.map((x,i)=>({i,matches:g.map((y,j)=>({j,y})).filter(({y})=>strict?overlap(x,y)>0:substantial(x,y))})).filter(x=>new Set(x.matches.map(({y})=>y.job_no)).size>1).map(x=>x.i);
  const merges=merged(false),splits=g.map(x=>p.filter(y=>substantial(y,x)).length),pairs=monotoneMatch(p,g,(x,y)=>overlap(x,y)>0?iou(x,y):null),usedG=new Set(pairs.map(x=>x[1])),usedP=new Set(pairs.map(x=>x[0]));
  const boundaries=xs=>[...new Set(xs.flatMap(x=>[x.start_s,x.end_s]).filter(x=>x>0&&x<d))].sort((a,b)=>a-b),pb=boundaries(p),gb=boundaries(g);
  const boundary=Object.fromEntries([1,3,5].map(t=>{const ps=monotoneMatch(pb,gb,(x,y)=>Math.abs(x-y)<=t?-Math.abs(x-y):null);return [t,{pairs:ps.map(([i,j])=>({predicted:pb[i],gt:gb[j]})),missed:gb.length-ps.length,extra:pb.length-ps.length,recall:ratio(ps.length,gb.length),precision:ratio(ps.length,pb.length),absolute_error_s:quantiles(ps.map(([i,j])=>Math.abs(pb[i]-gb[j])))}];}));
  const gf=frames(g,d),counts=p.map(()=>({}));let pi=0;gf.forEach((l,n)=>{while(pi+1<p.length&&n/10>=p[pi].end_s)pi++;counts[pi][l]=(counts[pi][l]||0)+1;});
  const continuous=p.map(x=>{const c={};g.forEach(y=>c[label(y)]=(c[label(y)]||0)+overlap(x,y));return c;});
  return {status:'MEASURED',raw_interval_count:p.length,gt_occurrences:g.length,merged:ratio(merges.length,p.length),merged_ids:merges.map(i=>p[i].segment_id),strict_merged:ratio(merged(true).length,p.length),split:ratio(splits.filter(n=>n>=2).length,g.length),split_excess:sum(splits,n=>Math.max(0,n-1)),missed:ratio(g.length-usedG.size,g.length),excess:p.length-usedP.size,hidden_by_merge:g.filter((x,j)=>!usedG.has(j)&&merges.some(i=>substantial(p[i],x))).length,pairs: pairs.map(([i,j])=>({predicted_id:p[i].segment_id,gt_id:g[j].gt_segment_id??String(j),start_error_s:Math.abs(p[i].start_s-g[j].start_s),end_error_s:Math.abs(p[i].end_s-g[j].end_s),duration_error_s:Math.abs(duration(p[i])-duration(g[j]))})),boundary,oracle_MoF:ratio(sum(counts,c=>Math.max(0,...Object.values(c))),gf.length),oracle_continuous:ratio(sum(continuous,c=>Math.max(0,...Object.values(c))),d),oracle_labels:counts.map(c=>Object.entries(c).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0]??null)};
}
export function intervalErrors(pred,gt){return pred.map(p=>{const c={};gt.forEach(g=>{const l=label(g);c[l]=(c[l]||0)+overlap(p,g);});const wrong=gt.filter(g=>label(g)!==label(p)).reduce((n,g)=>n+overlap(p,g),0),majority=Object.entries(c).sort((a,b)=>b[1]-a[1]||(a[0]<b[0]?-1:a[0]>b[0]?1:0))[0]?.[0];return {...p,duration:duration(p),wrong_seconds:wrong,E:wrong>0,majority_error:label(p)!==majority};});}
export function checkSafetyNet(pred,gt,d,{status='succeeded'}={}){
  if(['communication_failed','cancelled','not_run'].includes(status))return {status,metrics:null};
  const rows=status==='invalid'?[{segment_id:'__INVALID__',job_no:'__INVALID__',job_title:'__INVALID__',start_s:0,end_s:d,review_required:true,review_reasons:['invalid_contract'],forced_low_confidence:false,confidence_raw:null,confidence:null}]:pred;
  const errors=intervalErrors(rows,gt),N=errors.length,R=errors.filter(p=>p.review_required),A=errors.filter(p=>!p.review_required),E=errors.filter(p=>p.E),ER=R.filter(p=>p.E),EA=A.filter(p=>p.E);
  const bins=(xs,key)=>Array.from({length:10},(_,i)=>{const group=xs.filter(p=>Number.isFinite(p[key])&&Math.min(9,Math.floor(p[key]*10))===i);return {lower:i/10,upper:(i+1)/10,upper_inclusive:i===9,count:group.length,correct:ratio(group.filter(p=>!p.E).length,group.length),mean_raw:group.length?sum(group,p=>p.confidence_raw)/group.length:null,time_agreement:ratio(sum(group,p=>p.duration-p.wrong_seconds),sum(group,p=>p.duration))};});
  const reasons=[...new Set(errors.flatMap(p=>p.review_reasons||[]))];
  return {status,errors:errors.map(({segment_id,E,majority_error,wrong_seconds,review_required,review_reasons})=>({segment_id,E,majority_error,wrong_seconds,review_required,review_reasons})),error_detection:ratio(ER.length,E.length),auto_error:ratio(EA.length,A.length),missed_all:ratio(EA.length,N),auto_rate:ratio(A.length,N),review_rate:ratio(R.length,N),auto_time:ratio(sum(A,p=>p.duration),d),review_time:ratio(sum(R,p=>p.duration),d),review_precision:ratio(ER.length,R.length),auto_wrong_seconds:ratio(sum(A,p=>p.wrong_seconds),sum(A,p=>p.duration)),raw_bins:{all:bins(errors,'confidence_raw'),unforced:bins(errors.filter(p=>!p.forced_low_confidence),'confidence_raw'),forced:bins(errors.filter(p=>p.forced_low_confidence),'confidence_raw')},display_bins:bins(errors,'confidence'),factors:Object.fromEntries(reasons.map(k=>{const xs=errors.filter(p=>p.review_reasons?.includes(k));return [k,{count:xs.length,errors:xs.filter(p=>p.E).length,uniquely_detected:xs.filter(p=>p.E&&p.review_reasons.length===1).length}];})),union_detected:ER.length};
}
export function aggregate(scores){const done=scores.filter(s=>s.completed),attempted=scores.filter(s=>s.attempted),matrix={};done.forEach(s=>Object.entries(s.confusion).forEach(([g,row])=>{matrix[g]??={};Object.entries(row).forEach(([p,n])=>matrix[g][p]=(matrix[g][p]||0)+n);}));return {planned:scores.length,attempted:attempted.length,remaining:scores.length-attempted.length,completion:ratio(done.filter(s=>s.status!=='invalid').length,scores.length),Acc:ratio(sum(done,s=>s.correct_frames),sum(done,s=>s.frame_count)),effective_Acc:ratio(sum(attempted,s=>s.correct_frames),sum(attempted,s=>s.frame_count)),Edit:done.length?sum(done,s=>s.Edit)/done.length:null,F1:Object.fromEntries([10,25,50].map(k=>{const tp=sum(done,s=>s.F1[k].tp),fp=sum(done,s=>s.F1[k].fp),fn=sum(done,s=>s.F1[k].fn);return [k,{tp,fp,fn,rate:ratio(2*tp,2*tp+fp+fn)}];})),confusion:matrix,...classMetrics(matrix)};}
export function fixedMetrics(pred,gt){const rows=gt.map((g,i)=>({g:label(g),p:pred?.[i]?label(pred[i]):'__INVALID__'})),matrix=confusion(rows.map(r=>r.g),rows.map(r=>r.p));return {accuracy:ratio(rows.filter(r=>r.g===r.p).length,rows.length),confusion:matrix,...classMetrics(matrix),errors:rows.flatMap((r,i)=>r.g===r.p?[]:[{gt_segment_id:gt[i].gt_segment_id,predicted_segment_id:pred?.[i]?.segment_id??null,expected:r.g,predicted:r.p}])};}
export function routineMetrics(pred,gt){const gtLabels=new Set(gt.map(label)),invented=pred.filter(p=>!gtLabels.has(label(p))),count=xs=>xs.reduce((a,s)=>(a[s.job_no]=(a[s.job_no]||0)+1,a),{}),compressed=xs=>xs.filter((s,i)=>!i||label(s)!==label(xs[i-1])),pg=count(pred),gg=count(gt),pc=count(compressed(pred)),gc=count(compressed(gt)),keys=[...new Set([...Object.keys(pg),...Object.keys(gg)])];return {invented_segments:invented.length,invented_seconds:sum(invented,duration),occurrences:Object.fromEntries(keys.map(k=>[k,{gt_raw:gg[k]||0,predicted_raw:pg[k]||0,raw_difference:(pg[k]||0)-(gg[k]||0),gt_compressed:gc[k]||0,predicted_compressed:pc[k]||0,compressed_difference:(pc[k]||0)-(gc[k]||0)}])),human_order_audit:{status:'NOT_RUN',notes:null}};}
export function pairedEvidence(before,after,gt){const b=intervalErrors(before,gt),a=intervalErrors(after,gt);if(JSON.stringify(b.map(p=>[p.segment_id,p.start_s,p.end_s]))!==JSON.stringify(a.map(p=>[p.segment_id,p.start_s,p.end_s])))throw new Error('INCOMPATIBLE_STAGE1');const compare=key=>({corrected:b.filter((p,i)=>p[key]&&!a[i][key]).map(p=>p.segment_id),regressed:b.filter((p,i)=>!p[key]&&a[i][key]).map(p=>p.segment_id)});return {strict:compare('E'),majority:compare('majority_error')};}
export function windowScores(pred,gt,windows,videoId){return windows.filter(w=>w.video_id===videoId).map(w=>{const crop=xs=>xs.filter(s=>overlap(s,w)>0).map(s=>({...s,start_s:Math.max(s.start_s,w.start_s)-w.start_s,end_s:Math.min(s.end_s,w.end_s)-w.start_s}));return {window:w,score:scoreTAS(crop(pred),crop(gt),duration(w))};});}
