import {demand,sha256} from './core.js';
export function validatePriceTable(table){demand(table?.schema_version==='geap-price-table.v1'&&typeof table.version==='string'&&typeof table.currency==='string'&&typeof table.source==='string'&&typeof table.confirmed_at==='string'&&Array.isArray(table.models),'INVALID_PRICE_TABLE','料金表の出典・確認日・通貨・版が必要です。');for(const m of table.models){demand(typeof m.model_id==='string'&&m.components?.length&&m.coverage_confirmed===true,'INVALID_PRICE_TABLE','モデルと課金内訳の確認が必要です。');for(const c of m.components)demand(typeof c.usage_field==='string'&&Number.isFinite(c.price)&&c.price>=0&&Number.isFinite(c.unit)&&c.unit>0&&typeof c.description==='string','INVALID_PRICE_TABLE','課金項目・単価・単位が必要です。');}return table;}
// Prices and usage meanings must be supplied explicitly; no inferred image split,
// cached-token discounts or reasoning-token treatment.
export function estimateCost(attempts,table,{mock=false,attributedStage1=[]}={}){
  const unknown=reason=>({total:null,status:'unknown',cost_status:'unknown',currency:table?.currency??null,price_table:table?{version:table.version,sha256:sha256(table),source:table.source,confirmed_at:table.confirmed_at}:null,formula:null,reason,actual_spend:null,standalone_attribution:null});
  if(mock)return unknown('疑似使用量。実費・精度は未測定。');if(!table)return unknown('料金表が未設定です。');validatePriceTable(table);
  function calculate(xs){let total=0;const details=[];for(const a of xs){const model=table.models.find(m=>m.model_id===a.model_id);if(!model||!a.usageMetadata)return null;for(const c of model.components){const count=c.usage_field.split('.').reduce((v,k)=>v?.[k],a.usageMetadata);if(!Number.isFinite(count)||count<0)return null;const cost=count/c.unit*c.price;details.push({attempt_id:a.attempt_id,model_id:a.model_id,usage_field:c.usage_field,count,unit:c.unit,price:c.price,cost});total+=cost;}}return {total,details};}
  const spent=calculate(attempts),standalone=calculate([...attempts,...attributedStage1]);if(!spent||!standalone)return unknown('失敗試行を含む使用量・モデル単価または必須内訳が不明です。');return {total:spent.total,status:'estimated',cost_status:'estimated',currency:table.currency,price_table:{version:table.version,sha256:sha256(table),source:table.source,confirmed_at:table.confirmed_at},formula:'sum(reported_usage_field / explicit_unit * explicit_price)',reason:'設定された料金表による概算。請求確定額ではありません。',actual_spend:spent,standalone_attribution:standalone};
}
